package:
  name: imp
  version: "2.14.0"

source:
  fn: imp-2.14.0.tar.gz [not win]
  url: https://integrativemodeling.org/2.14.0/download/imp-2.14.0.tar.gz [not win]
  sha256: 67c7b5c4a57949786cd65d9f918694b59c9f11f5cf1515b8d13970a908e58126 [not win]
  fn: imp-2.14.0.zip [win]
  url: https://integrativemodeling.org/2.14.0/download/imp-2.14.0.zip [win]
  sha256: 64f3f44b45c5b8844c8249f0dba340833b1c2d20e66b74496fb48714fabc93f6 [win]
  patches:
    - imp-directories.patch [win64]
    - vs2008-ice-dos.patch [win and py27]

build:
  number: 0
  detect_binary_files_with_prefix: True [not win]

requirements:
  host:
    - python {{ python }}
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python {{ python }}
    - swig
    - cgal 4.12.* [win and py27]
    - cgal 4.14.* [osx or (py < 38 and (not win or not py27))]
    - cgal 5.0.2.* [py >= 38 and not osx]
    - eigen
    - cmake [not win or not py27]
    - cmake-mac [win and py27]
    - boost 1.67.0.* [py < 38]
    - boost 1.71.0.* [py >= 38]
    - hdf5 1.10.2.* [py < 38 and not linux64]
    - hdf5 1.10.4.* [py >= 38 or linux64]
    - fftw 3.3.4.* [win]
    - fftw 3.3.8.* [not win]
    - libtau 1.0.1.* [win]
    - libtau 1.0.2.* [not win]
    - gsl 1.8.* [win]
    - gsl 2.4.* [not win]
    - opencv 3.4.2.* [not win and not (osx and py >= 38)]
    - protobuf 3.6.1.* [linux32]
    - protobuf 3.11.4.* [not win and not linux32 and py > 27]
    - protobuf 3.11.2.* [not win and not linux32 and py == 27]
    - opencv 4.0.1.* [win64 and not py27 and py >= 38]
    - opencv 3.4.1.* [win64 and not py27 and py < 38]
    - opencv 3.4.2.* [win32 and not py27 and py < 38]
    - opencv-nopython 2.4.9.* [(win and py27) or (osx and py >= 38) or (win32 and py >= 38)]
    - protobuf 3.5.2.* [win and py27]
    - protobuf 3.6.1.* [win and not py27 and py < 38]
    - protobuf 3.12.4.* [win and not py27 and py >= 38]
    - openmpi 4.0.2.* [osx]
    - mpich2 1.4.1.* [linux32]
    - mpich 3.2.1.* [linux64 and py < 38]
    - mpich 3.3.2.* [linux64 and py >= 38]
      # For windows, need to install Microsoft MPI

  run:
    - python {{ python }}
    - cgal 4.12.* [win and py27]
    - cgal 4.14.* [osx or (py < 38 and (not win or not py27))]
    - cgal 5.0.2.* [py >= 38 and not osx]
    - boost 1.67.0.* [py < 38]
    - boost 1.71.0.* [py >= 38]
    - libboost 1.71.0.* [py >= 38]
    - libboost 1.67.0.* [py < 38]
    - hdf5 1.10.2.* [py < 38 and not linux64]
    - hdf5 1.10.4.* [py >= 38 or linux64]
    - fftw 3.3.4.* [win]
    - fftw 3.3.8.* [not win]
    - libtau 1.0.1.* [win]
    - libtau 1.0.2.* [not win]
    - gsl 1.8.* [win]
    - gsl 2.4.* [not win]
    - opencv 3.4.2.* [not win and not (osx and py >= 38)]
    - protobuf 3.6.1.* [linux32]
    - protobuf 3.11.4.* [not win and not linux32 and py > 27]
    - protobuf 3.11.2.* [not win and not linux32 and py == 27]
    - opencv 4.0.1.* [win64 and not py27 and py >= 38]
    - opencv 3.4.1.* [win64 and not py27 and py < 38]
    - opencv 3.4.2.* [win32 and not py27 and py < 38]
    - opencv-nopython 2.4.9.* [(win and py27) or (osx and py >= 38) or (win32 and py >= 38)]
    - protobuf 3.5.2.* [win and py27]
    - protobuf 3.6.1.* [win and not py27 and py < 38]
    - protobuf 3.12.4.* [win and not py27 and py >= 38]
    - llvm-openmp [osx]
    - openmpi 4.0.2.* [osx]
    - mpich2 1.4.1.* [linux32]
    - mpich 3.2.1.* [linux64 and py < 38]
    - mpich 3.3.2.* [linux64 and py >= 38]

test:
  # Need Eigen to test IMPConfig.cmake
  requires:
    - eigen
  # Python imports
  imports:
    - IMP
    - IMP.atom
    - IMP.cgal
    - IMP.cnmultifit
    - IMP.em2d
    - IMP.npc
    - IMP.npctransport
    - IMP.bayesianem
    - IMP.sampcon
    - IMP.rmf
    - IMP.mpi
    - IMP.spb
    - RMF
  # Command line tools
  commands:
    - cnmultifit --help
    - foxs --help
    - spb_test_score --help

about:
  home: https://integrativemodeling.org
  license: LGPL/GPL
  summary: "The Integrative Modeling Platform"
  description: >
    IMP's broad goal is to contribute to a comprehensive structural
    characterization of biomolecules ranging in size and complexity from small
    peptides to large macromolecular assemblies, by integrating data from
    diverse biochemical and biophysical experiments. IMP provides an open
    source C++ and Python toolbox for solving complex modeling problems, and a
    number of applications for tackling some common problems in a user-friendly
    way. IMP can also be used from the
    [Chimera](http://www.cgl.ucsf.edu/chimera/) molecular modeling system,
    or via one of several web applications.

    See [the IMP website](https://integrativemodeling.org/) for more details.

    If you have problems with this conda package, please
    [open an issue](https://github.com/salilab/conda-recipes/issues).
