# To make a nightly build package, set version to date (e.g. '20210413')
# and nightly_hash to the corresponding git hash (e.g. '182d9373c4')
{% set version = "2.19.0" %}
{% set nightly_hash = '' %}


package:
{% if nightly_hash == '' %}
  name: imp
{% else %}
  name: imp-nightly
{% endif %}
  version: {{ version }}

source:
{% if nightly_hash == '' %}
  fn: imp-{{ version }}.tar.gz
  url: https://integrativemodeling.org/{{ version }}/download/imp-{{ version }}.tar.gz
  sha256: 75529285e6d94ffe5b4246097d70e223d984947193226b39313c1a85bc011ddd
{% else %}
  fn: imp-{{ version }}.develop.{{ nightly_hash }}.tar.gz
  url: https://integrativemodeling.org/nightly/download/imp-{{ version }}.develop.{{ nightly_hash }}.tar.gz
{% endif %}
  patches:
    - imp-directories.patch  # [win]

build:
  number: 0
  detect_binary_files_with_prefix: True  # [not win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - protobuf {{ libprotobuf }}             # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - pkg-config   # [not win]
    - swig
    - cmake
    - ninja
  host:
    - python
    - numpy
    # RMF and IHM are only built for Python 3
    - rmf >=1.4  # [py > 27]
    - ihm  # [py > 27]
    - libboost-devel  # [py > 27]
    - boost-cpp # [py == 27]
    - hdf5
    # We need both the libprotobuf library and the Python wrappers
    - libprotobuf
    - protobuf # [py > 27]
    - protobuf >=3.11.0  # [py == 27]
    # We only need the library; we don't use the OpenCV Python wrappers
    - libopencv
    # We don't need matplotlib to build IMP, but we include it here so that
    # the resulting IMP package can be installed alongside matplotlib
    # (otherwise IMP pulls in a newer Boost, which is incompatible)
    - matplotlib   # [py == 27]
    - eigen
    - cereal
    # Force usage of conda-forge fftw, not salilab
    - fftw >3.3.4
    - libtau
    - gsl
    - libcblas
    - cgal-cpp
    # CGAL code pulls in mpfr and gmp (on Linux/Mac) or mpir (on Windows)
    - gmp   # [not win]
    - mpir  # [win]
    - mpfr
    - mpich  # [not win]
    - msmpi  # [win]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    # RMF does not pin its exports, but we link against the C++ DSO
    - {{ pin_compatible('rmf', max_pin='x.x') }}  # [py > 27]
    - ihm  # [py > 27]
    - {{ pin_compatible('boost-cpp', max_pin='x.x.x') }} # [py == 27]
    - {{ pin_compatible('libtau', max_pin='x.x') }}
    # We use pathlib which is part of the standard library in Python 3,
    # but in a separate package in Python 2
    - pathlib   # [py == 27]
    - protobuf
    - msmpi  # [win]

test:
  # Need Eigen to test IMPConfig.cmake
  requires:
    - eigen
  # Python imports
  imports:
    - IMP
    - IMP.atom
    - IMP.cgal
    - IMP.em2d
    - IMP.npc
    - IMP.npctransport
    - IMP.bayesianem
    - IMP.sampcon
    - IMP.rmf
    - IMP.mpi
    - IMP.spb
    - IMP.cnmultifit
    - RMF
  # Command line tools
  commands:
    - foxs --help
    - spb_test_score --help
    - cnmultifit --help
    - imp_sampcon --help
    - multifit --help

about:
  home: https://integrativemodeling.org
  license: GPL-3.0-or-later
  license_file:
    - COPYING.LGPL
    - COPYING.GPL
  summary: "The Integrative Modeling Platform"
  description: >
    IMP's broad goal is to contribute to a comprehensive structural
    characterization of biomolecules ranging in size and complexity from small
    peptides to large macromolecular assemblies, by integrating data from
    diverse biochemical and biophysical experiments. IMP provides an open
    source C++ and Python toolbox for solving complex modeling problems, and a
    number of applications for tackling some common problems in a user-friendly
    way. IMP can also be used from the
    [Chimera](https://www.cgl.ucsf.edu/chimera/) molecular modeling system,
    or via one of several web applications.

    See [the IMP website](https://integrativemodeling.org/) for more details.

    If you have problems with this conda package, please
    [open an issue](https://github.com/salilab/conda-recipes/issues).
  doc_url: https://integrativemodeling.org/doc.html
  dev_url: https://github.com/salilab/imp/

extra:
  recipe-maintainers:
    - benmwebb
