:: Find packages in Anaconda locations
set CMAKE_PREFIX_PATH=%LIBRARY_PREFIX%

mkdir build
cd build
cmake -DWITH_PYTHON=OFF -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% -DWITH_CUDA=OFF -DWITH_AVFOUNDATION=OFF -DWITH_FFMPEG=OFF -DJPEG_INCLUDE_DIR:PATH=%LIBRARY_INC% -DJPEG_LIBRARY:FILEPATH=%LIBARY_LIB%\libjpeg.lib -DPNG_PNG_INCLUDE_DIR:PATH=%LIBRARY_INC% -DPNG_LIBRARY:FILEPATH=%LIBRARY_LIB%\libpng.lib -DZLIB_INCLUDE_DIR:PATH=%LIBRARY_INC% -DZLIB_LIBRARY:FILEPATH=%LIBRARY_LIB%\zlib.lib -G"NMake Makefiles" ..
if errorlevel 1 exit 1

nmake
if errorlevel 1 exit 1

nmake install
if errorlevel 1 exit 1
