# Tested on Mac OS X 10.9 using clang compiler provided by XCode
package:
    name: opencv-nopython
    version: 2.4.9

source:
    fn: opencv-2.4.9.zip
    url: http://downloads.sourceforge.net/project/opencvlibrary/opencv-unix/2.4.9/opencv-2.4.9.zip
    sha256: 803010848154988e9cbda8b3fa857fcbb27382c2946ed729e1a7e40600bb4c71

build:
    number: 7
    features:
      - vc9 [win and py27]
      - vc14 [win and py35]

requirements:
    build:
        - python [win]
        - cmake [not win]
        - cmake-mac [win]
        - jpeg 9b.*
        - zlib 1.2.11.*
        - libpng 1.6.37.*
        - libtiff 4.1.0.*
    run:
        - jpeg 9b.*
        - zlib 1.2.11.*
        - libpng 1.6.37.*
        - libtiff 4.1.0.*

about:
    home: http://opencv.org/
    summary: "opencv package built without Python (for Python 3)"
    license: BSD
