package:
  name: mdt
  version: "5.4"

source:
  fn: mdt-5.4.tar.gz
  url: https://salilab.org/mdt/5.4/mdt-5.4.tar.gz
  sha256: fc403b8c26365c11bd9522929aef0c3b51dff860fddc8ac446a980acec5a3d44

build:
  number: 4

requirements:
  host:
    - python {{ python }}
    - numpy
    - modeller 9.23.*
    - glib
  build:
    - {{ compiler('c') }}
    - python {{ python }}
    - cmake [not osx]
    - cmake-mac [osx]
    - swig
  run:
    - python {{ python }}
    - numpy
    - modeller 9.23.*

about:
  home: https://salilab.org/mdt/
  license: GPL2
  summary: "Generate frequency tables used by Modeller and IMP"
  description: >
    MDT prepares a raw frequency table, given information from MODELLER
    alignments and/or PDB files. More precisely, MDT uses a sample of
    sequences, structures, and/or alignments to construct a table
    N(a,b,c,...,d) for features a, b, c, ..., d. The sample for generating
    the frequencies N is obtained depending on the type of features
    a, b, c, ..., d. The sample can contain individual proteins, pairs
    of proteins, pairs of residues in proteins, pairs of aligned residues,
    pairs of aligned pairs of residues, chemical bonds, angles, dihedral
    angles, and pairs of tuples of atoms. Some features work with triple
    alignments, too. All the needed features a, b, c, ..., d are calculated
    automatically from the sequences, alignments, and/or PDB files.
    The feature bins are defined by the user when each feature is created.

    See the [MDT website](https://salilab.org/mdt/) for more information.

    If you have problems with this conda package, please
    [open an issue](https://github.com/salilab/conda-recipes/issues).
