package:
  name: mdt
  version: "5.5"

source:
  fn: mdt-5.5.tar.gz
  url: https://salilab.org/mdt/5.5/mdt-5.5.tar.gz
  sha256: 94b3dbd3050be14568ed613cc1d534e11ef37cb32a646116f35ef66cab5c187c
  patches:
    - mdt-hdf5-hl.patch
    - mdt-cmake.patch

build:
  number: 8

requirements:
  host:
    - python {{ python }}
    - numpy
    - modeller 10.6.*
    - glib
  build:
    - {{ compiler('c') }}
    - python {{ python }}
    - cmake
    - swig
  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - modeller 10.6.*

about:
  home: https://salilab.org/mdt/
  license: GPL2
  summary: "Generate frequency tables used by Modeller and IMP"
  description: >
    MDT prepares a raw frequency table, given information from MODELLER
    alignments and/or PDB files. More precisely, MDT uses a sample of
    sequences, structures, and/or alignments to construct a table
    N(a,b,c,...,d) for features a, b, c, ..., d. The sample for generating
    the frequencies N is obtained depending on the type of features
    a, b, c, ..., d. The sample can contain individual proteins, pairs
    of proteins, pairs of residues in proteins, pairs of aligned residues,
    pairs of aligned pairs of residues, chemical bonds, angles, dihedral
    angles, and pairs of tuples of atoms. Some features work with triple
    alignments, too. All the needed features a, b, c, ..., d are calculated
    automatically from the sequences, alignments, and/or PDB files.
    The feature bins are defined by the user when each feature is created.

    See the [MDT website](https://salilab.org/mdt/) for more information.

    If you have problems with this conda package, please
    [open an issue](https://github.com/salilab/conda-recipes/issues).
