package:
  name: rmf
  version: "1.6"

source:
  fn: rmf-1.6.zip
  url: https://salilab.org/~ben/rmf-1.6.zip

build:
  number: 0

requirements:
  host:
    - python {{ python }}
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python {{ python }}
    - numpy 1.23.*
    - swig
    - cmake
    - boost 1.82.0.*
    - hdf5 1.12.1.*

  run:
    - python {{ python }}

about:
  home: https://github.com/salilab/rmf/
  license: Apache
  summary: The library to support reading and writing of RMF files
