{% set name = "rmf" %}
{% set version = "1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/salilab/rmf/archive/93c97f15fc70a3377c2fcfbd49908ba19e8e14ce.zip
  sha256: 8739533ef0395924a88755838dc717d837b8c7aa979820d161264fc060ee0841

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - swig
    - cmake
    - ninja
  host:
    - python
    - boost
    - hdf5
  run:
    - python
    - boost
    - hdf5

test:
  imports:
    - RMF
  commands:
    - rmf3_dump --version

about:
  home: https://integrativemodeling.org/rmf/
  summary: Library to support reading and writing of RMF files
  license: Apache
  license_file: COPYING
  description: |
    This library provides support for the RMF file format for storing
    hierarchical molecular data (such as atomic or coarse grained
    representations of proteins), along with markup, including geometry
    and score data.
  doc_url: https://integrativemodeling.org/rmf/
  dev_url: https://github.com/salilab/rmf/

extra:
  recipe-maintainers:
    - benmwebb
