package:
  name: modeller
  version: "10.4"

source:
  fn: modeller-10.4-mac.pax.gz [osx]
  url: https://salilab.org/modeller/10.4/modeller-10.4-mac.pax.gz [osx]
  sha256: 9dbd905406755cade5ed11672042cd441bd7251e1feb66e5319ab226ba2cf618 [osx]
  fn: modeller-10.4.tar.gz [linux]
  url: https://salilab.org/modeller/10.4/modeller-10.4.tar.gz [linux]
  sha256: ed08fcbbee1db095a2c243028b567569398e03dabfe2ad459dca1a5298bb8ac9 [linux]
  fn: modeller10.4-32bit.zip [win32]
  url: https://salilab.org/modeller/10.4/modeller10.4-32bit.zip [win32]
  sha256: 60ecde4dfcc060134e43adbd02123ee3eeff2d04fcd00f91929d857b0219a4ee [win32]
  fn: modeller10.4-64bit.zip [win64]
  url: https://salilab.org/modeller/10.4/modeller10.4-64bit.zip [win64]
  sha256: 0e08744f1814fb21466403a4fcca52cb5819645bd596cbcd43d1174ddcd458d4 [win64]
  patches:
    # On Mac pax.gz isn't extracted before patching, so we have to apply
    # this patch ourselves in build.sh
    - search-path.patch [not osx]

build:
  number: 0
  rpaths: [linux]
    - lib/modeller-10.4/lib/x86_64-intel8/ [linux64]
    - lib/modeller-10.4/lib/i386-intel8/ [linux32]
    - lib/hdf5-1107 [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - swig [unix]
  host:
    - python
    - setuptools
    - pkg-config [unix]
    - hdf5-1107 [unix]
    - glib >=2.68.1 [osx]
    - glib 2.31.2 [linux]
  run:
    - python
    - hdf5-1107 [unix]

test:
  requires:
    - pkg-config [unix]
  # Command line tool
  commands:
    - mod10.4 --cflags --libs
    - pkg-config --cflags --libs modeller [unix]
  # Python imports (cannot test without license key)
  #imports:
  #  - modeller

about:
  home: https://salilab.org
  license: Free for academic use
  summary: "Comparative modeling by satisfaction of spatial restraints"
  description: >
    MODELLER is used for homology or comparative modeling of protein
    three-dimensional structures (1,2). The user provides an alignment of a
    sequence to be modeled with known related structures and MODELLER
    automatically calculates a model containing all non-hydrogen atoms.
    MODELLER implements comparative protein structure modeling by satisfaction
    of spatial restraints (3,4), and can perform many additional tasks,
    including de novo modeling of loops in protein structures, optimization
    of various models of protein structure with respect to a flexibly defined
    objective function, multiple alignment of protein sequences and/or
    structures, clustering, searching of sequence databases, comparison of
    protein structures, etc.

    1. B. Webb, A. Sali. Comparative Protein Structure Modeling Using Modeller.
       Current Protocols in Bioinformatics 54, John Wiley & Sons, Inc.,
       5.6.1-5.6.37, 2016.

    2. M.A. Marti-Renom, A. Stuart, A. Fiser, R. Sánchez, F. Melo, A. Sali.
       Comparative protein structure modeling of genes and genomes.
       Annu. Rev. Biophys. Biomol. Struct. 29, 291-325, 2000.

    3. A. Sali & T.L. Blundell. Comparative protein modelling by satisfaction
       of spatial restraints. J. Mol. Biol. 234, 779-815, 1993.

    4. A. Fiser, R.K. Do, & A. Sali. Modeling of loops in protein structures,
       Protein Science 9. 1753-1773, 2000.

    See [the Modeller website](https://salilab.org/modeller/) for more details.

    If you have problems with this conda package, please
    [open an issue](https://github.com/salilab/conda-recipes/issues).
