{% set version = "2.14.0" %}

package:
  name: imp
  version: {{ version }}

source:
  fn: imp-{{ version }}.tar.gz
  url: https://integrativemodeling.org/{{ version }}/download/imp-{{ version }}.tar.gz
  sha256: 67c7b5c4a57949786cd65d9f918694b59c9f11f5cf1515b8d13970a908e58126
  patches:
    - clang18.patch
    - clang-10-omp.patch
    - boost-1.75.patch
    - cmake-2.8.12.patch
    - imp-directories.patch [win]
    - vs2008-ice.patch [win and py == 27]

build:
  number: 0
  detect_binary_files_with_prefix: True [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config [not win]
    - swig
    - cmake
    - ninja
  host:
    - python
    - numpy
    - rmf
    - ihm
    - boost-cpp
    - hdf5
    - protobuf
    - libopencv
    - eigen
    - fftw
    - gsl
    - cgal
    - gmp
    - mpfr
    - openmpi [osx]
    - mpich2 [linux32]
    - mpich [linux64]
      # For windows, need to install Microsoft MPI

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - ihm
    - rmf
    - boost-cpp
    - hdf5
    - fftw
    - gsl
    - gmp
    - mpfr
    - libopencv
    - protobuf
    - llvm-openmp [osx]
    - openmpi [osx]
    - mpich2 [linux32]
    - mpich [linux64]

test:
  # Need Eigen to test IMPConfig.cmake
  requires:
    - eigen
  # Python imports
  imports:
    - IMP
    - IMP.atom
    - IMP.cgal
    - IMP.multifit
    - IMP.em2d
    - IMP.npc
    - IMP.npctransport
    - IMP.bayesianem
    - IMP.sampcon
    - IMP.rmf
    - IMP.mpi
    - IMP.spb
    - RMF
  # Command line tools
  commands:
    - multifit --help
    - foxs --help
    - spb_test_score --help

about:
  home: https://integrativemodeling.org
  license: LGPL-2.0-or-later
  license_file: COPYING.LGPL
  summary: "The Integrative Modeling Platform"
  description: >
    IMP's broad goal is to contribute to a comprehensive structural
    characterization of biomolecules ranging in size and complexity from small
    peptides to large macromolecular assemblies, by integrating data from
    diverse biochemical and biophysical experiments. IMP provides an open
    source C++ and Python toolbox for solving complex modeling problems, and a
    number of applications for tackling some common problems in a user-friendly
    way. IMP can also be used from the
    [Chimera](http://www.cgl.ucsf.edu/chimera/) molecular modeling system,
    or via one of several web applications.

    See [the IMP website](https://integrativemodeling.org/) for more details.

    If you have problems with this conda package, please
    [open an issue](https://github.com/salilab/conda-recipes/issues).
  doc_url: https://integrativemodeling.org/doc.html
  dev_url: https://github.com/salilab/imp/

extra:
  recipe-maintainers:
    - benmwebb
