package:
  name: libtau
  version: "1.0.2"

source:
  fn: libTAU-src-1.0.2.tar.gz
  # Source is not public; manually copy the .tar.gz into conda src_cache
  url: https://integrativemodeling.org/libTAU/libTAU-src-1.0.2.tar.gz
  patches:
    - scons-env.patch [osx]

build:
  number: 0
  features:
    - vc9 [win and py27]
    - vc14 [win and py35]

requirements:
  build:
    - scons
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python [win]
    - boost

about:
  home: https://integrativemodeling.org/libTAU.html
  license: Binary distribution only
  summary: "Support library needed for MultiFit"
  description: >
    libTAU is a support library needed for MultiFit, provided by
    [Haim Wolfson's group](http://bioinfo3d.cs.tau.ac.il/) at
    [Tel Aviv University](https://www.tau.ac.il/). It is not open source,
    but we have permission to distribute its binaries with MultiFit and IMP.

    See [the libTAU website](https://integrativemodeling.org/libTAU.html)
    for more details.

    If you have problems with this conda package, please
    [open an issue](https://github.com/salilab/conda-recipes/issues).
